export const GET_POPULATION_START = 'GET_POPULATION_START';
export const GET_POPULATION_SUCCESS = 'GET_POPULATION_SUCCESS';
export const GET_POPULATION_ERROR = 'GET_POPULATION_ERROR';

export const REMOVE_POPULATION = 'REMOVE_POPULATION';

export const GET_PREFECTURES_START = 'GET_PREFECTURES_START';
export const GET_PREFECTURES_SUCCESS = 'GET_PREFECTURES_SUCCESS';
export const GET_PREFECTURES_ERROR = 'GET_PREFECTURES_ERROR';
